### ISSUE TITLE
If the username is too long, the objects are intertwined

### ISSUE THREAD

**Issue by tolgaaaltas** [clarkwinkelmann/flarum-ext-who-read#1]
If the username is too long, the objects are intertwined.

Title example:
![Title](https://i.ibb.co/drYmRjT/image.png)

Post example:
![Post](https://i.ibb.co/KbGG8DB/image.png)

**Comment by littlegolden** [comment]
Solution:
```css
.WhoRead--extended .WhoRead-user {
    text-align: center;
    text-overflow: ellipsis;
    max-width: 10em;
    overflow: hidden;
    white-space: nowrap;
}
```
